### ISSUE TITLE
Cannot find module './interface' from/node_modules/ethers/dist

### ISSUE THREAD

**Issue by amaurer** [0xProject/0x-monorepo#1107]
## Expected Behavior

I'm running browserify to export 0x libraries like so..
`browserify webbundle.js --standalone ZeroEx -o ./assets/0x.1.0.6.js`

## Current Behavior

`Cannot find module './interface' from ./node_modules/@0xproject/contract-wrappers/node_modules/ethers/dist'`
Looking in the directory, the file interface doesn't exist.  It does exist in 

## Possible Solution

This worked well on 1.0.5 release where dependency in contract-wrappers was "ethers": "3.0.22". Currently, set to "ethers": "4.0.0-beta.14" with 1.0.6 release.

I tried upgrading to ethers: 4.0.1 but ran into similar issue. 
`'./utils/properties' from './node_modules/@0xproject/contract-wrappers/node_modules/ethers/dist'`

## Steps to Reproduce 

```
1. npm install 0x.js@1.0.5
2. `browserify webbundle.js --standalone ZeroEx -o ./assets/0x.1.0.5.js` (or verify node_modules/@0xproject/contract-wrappers/package.json:dependencies)
3. npm install 0x.js@1.0.6
4. `browserify webbundle.js --standalone ZeroEx -o ./assets/0x.1.0.5.js`  (or verify node_modules/@0xproject/contract-wrappers/package.json:dependencies)
```

## Context

I want to get to version 1.0.6 with the inclusion of OrderWatcher with transactionHash.  

## Your Environment

|             Package | Version |
| ------------------: | :------ |
|             `0x.js` |1.0.6 |
| `Exchange Contract` | v2      |

**Comment by amaurer** [comment]
After playing with it a bit longer, it looks like this issue arises after installing *connect*
`npm i @0xproject/connect@2.0.4` works for my build
`npm i @0xproject/connect`  does not - (3.0.0)

**Comment by amaurer** [comment]
I switched over to using webpack and I was able to export the connect library along with ZeroEx.  While this isn't a 0x issue, it is possible that there is further support by upgrading to ethers@4.0.1 as described in issue #1111 .  Closing this issue and promoting #1111
